# Generated by Django 3.2.4 on 2023-01-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_github',
            new_name='dream_school',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_linkedin',
            new_name='major',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_website',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_youtube',
        ),
    ]
