# Generated by Django 3.2.4 on 2023-01-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230107_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dream_school',
            new_name='dream_School',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='major',
            new_name='intended_Major',
        ),
    ]
