# Generated by Django 3.2.4 on 2023-01-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_link',
            new_name='activity_list',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='source_link',
            new_name='award_list',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='sat_act',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='uwgpa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='wgpa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
