# Generated by Django 3.2.4 on 2023-01-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20230107_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='activity_list',
            new_name='Activity_List',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='award_list',
            new_name='Award_List',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sat_act',
            new_name='SAT_and_ACT',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='uwgpa',
            new_name='UNWEIGHTED_GPA',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='wgpa',
            new_name='WEIGHTED_GPA',
        ),
    ]
