# Generated by Django 3.2.4 on 2023-01-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20230107_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='SAT_and_ACT',
            new_name='SAT',
        ),
    ]
