# Generated by Django 3.2.4 on 2023-01-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20230107_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='SAT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='UNWEIGHTED_GPA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
